### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by TalinTheDev** [u1dm/dotfiles#1]
Hey!

I was checking out dotfiles for inspiration and saw yours. It's beautiful btw! I was wondering 1. what browser do you use? In the screenshots, correct me if I'm wrong but that's google chorme right? How'd you get it to look like that? Specifically the tabs?

Thanks!

**Comment by chernuha-dev** [comment]
> Hey!
> 
> I was checking out dotfiles for inspiration and saw yours. It's beautiful btw! I was wondering 1. what browser do you use? In the screenshots, correct me if I'm wrong but that's google chorme right? How'd you get it to look like that? Specifically the tabs?
> 
> Thanks!

Hoola, thx) im use google chrome, this is default chrome btw)

**Comment by u1dm** [comment]
> Hey!
> 
> I was checking out dotfiles for inspiration and saw yours. It's beautiful btw! I was wondering 1. what browser do you use? In the screenshots, correct me if I'm wrong but that's google chorme right? How'd you get it to look like that? Specifically the tabs?
> 
> Thanks!

Hoola, thx) im use google chrome, this is default chrome btw)
